# this program is for inserting bulk data into the database one by one from the datalist

import requests
import json

# Define the FastAPI endpoint URL
endpoint_url = "http://localhost:8000/add_modules_data"

# Define the data to be inserted in to the database
data_list = [
    {
        "text": "Document Analysis Module\nModule Overview\nThe Document Analysis module of ADVOCASE AI is designed to enhance the efficiency and accuracy of legal document reviews. It automates the analysis process, reducing time and effort while improving the reliability of the information extracted.\n\nKey Features\nRapid Document Comprehension: Reduces analysis time from 40 minutes to 2 minutes per document using advanced AI algorithms.\nProductivity Enhancement: Accelerates the review process, allowing legal professionals to focus on strategic tasks.\nDependability and Accuracy: Detects inconsistencies, errors, and anomalies, ensuring high accuracy in information extraction.\n\nBenefits\nTime Savings: Frees up valuable time for other legal responsibilities.\nIncreased Productivity: Streamlines the document analysis process.\nImproved Accuracy: Reduces the risk of human error.\n\nTechnical Capabilities\nMachine Learning Algorithms: Utilizes NLP and pattern recognition for thorough analysis.\nDocument Processing Workflow: Includes document upload, automated analysis, and report generation.\n\nUser Interaction\nUser-Friendly Interface: Easy navigation and customization options.\nDetailed Reports: Provides comprehensive reports for further legal review.\n\nImplementation Details\nIntegration: Compatible with existing legal practice management software.\nSecurity: Ensures data privacy and security.\nSupport: Comprehensive support and training resources available.\n\nUsage Scenarios\nContract Review\nCompliance Checks\nDue Diligence\n\nConclusion\nThe Document Analysis module revolutionizes the legal document review process, making it faster, more accurate, and highly efficient.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Document Analysis:\n\nFirst Step is to upload your document in any format and proceed.\n\nOur AI system will quickly review if the file is safe and meets the required conditions.\n\nAfter you accept credit deduction, our system will start processing your document.\n\nFinally, you can see the complete document analysis in various steps. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/_d3Z4n7osCk?si=3Z9_wR8D63iNY4QL"
    },
    {
        "text": "Case Analysis Module\nModule Overview\nThe Case Analysis module of ADVOCASE AI provides comprehensive tools for analyzing legal cases, identifying key issues, and deriving actionable insights.\n\nKey Features\nThorough Case Examination: Detailed analysis of case documents to highlight key issues.\nPattern Recognition: Identifies trends and patterns in case law.\nInsight Generation: Provides actionable insights based on case analysis.\n\nBenefits\nIn-depth Analysis: Ensures thorough understanding of case details.\nActionable Insights: Helps in formulating effective legal strategies.\nTrend Identification: Recognizes patterns in case law for strategic advantage.\n\nTechnical Capabilities\nAI Algorithms: Utilizes advanced algorithms for in-depth case analysis.\nData Integration: Integrates data from multiple sources for comprehensive analysis.\n\nUser Interaction\nInteractive Dashboard: User-friendly interface for easy navigation.\nCustomizable Reports: Tailored reports highlighting key findings.\n\nImplementation Details\nIntegration: Compatible with legal research databases.\nSecurity: Adheres to data privacy standards.\nSupport: Extensive support and training resources.\n\nUsage Scenarios\nLegal Strategy Formulation\nCase Preparation\nRisk Assessment\n\nConclusion\nThe Case Analysis module provides detailed and actionable insights, enabling legal professionals to make informed decisions.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Case Analysis:\n\nFirst step is to upload your document in any format and proceed.\n\nOur AI system will quickly check if the file is safe and meets the required conditions.\n\nAfter you accept the credit deduction, our system will start processing your document for analysis.\n\nNext, define your role in the case.\n\nOur system will then process your document based on your role.\n\nFinally, you will see the complete case analysis of your document, which you can also download for future reference.",
        "youtube_link" : "https://youtu.be/wrtdxOlY_4k?si=HiLCphJPGc8eBzTJ"
    },
    {
        "text": "Case Research Module\nModule Overview\nThe Case Research module of ADVOCASE AI enhances the efficiency and accuracy of legal research by automating the retrieval and analysis of relevant case law.\n\nKey Features\nAutomated Research: Quickly retrieves relevant case law based on search parameters.\nComprehensive Analysis: Analyzes cases to identify key points and precedents.\nReal-Time Updates: Provides the latest case law updates.\n\nBenefits\nTime Efficiency: Speeds up the research process.\nAccurate Results: Ensures comprehensive and relevant research outcomes.\nUp-to-Date Information: Keeps users informed with the latest legal developments.\n\nTechnical Capabilities\nAI-Powered Search: Uses AI to identify and retrieve relevant cases.\nData Analysis: Analyzes case details to highlight important information.\n\nUser Interaction\nSearch Interface: Easy-to-use search tools.\nDetailed Reports: Provides comprehensive research reports.\n\nImplementation Details\nIntegration: Compatible with legal research databases.\nSecurity: Ensures data privacy and compliance.\nSupport: Provides support and training resources.\n\nUsage Scenarios\nCase Preparation\nLegal Strategy Development\nPrecedent Identification\n\nConclusion\nThe Case Research module streamlines the legal research process, providing accurate and up-to-date information efficiently.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Case Research:\n\nFirst step is to upload your document in any format, describe your requirements, and proceed.\n\nOur AI system will quickly check if the file is safe and meets the required conditions.\n\nAfter you accept the credit deduction, our system will start processing your document for research.\n\nNext, chat with our system about your case to get better results. You can skip the chat after answering five questions.\n\nOur system will analyze your chat details and document.\n\nFinally, you will see the complete research details of your document, which you can also download for future reference.",
        "youtube_link" : "https://youtu.be/047Se8sTPjc?si=mxKtYEXNEpREcbme"
    },
    {
        "text": "Legal Drafter Module\nModule Overview\nThe Legal Drafter module of ADVOCASE AI is designed to streamline the creation of legal documents, ensuring precision, efficiency, and error-free drafting.\n\nKey Features\nAutomated Drafting: Generates legal drafts quickly with minimal manual input.\nTemplate Library: Offers a variety of templates for different legal documents.\nCustomization Options: Allows users to add detailed specifications and personal inputs.\n\nBenefits\nEnhanced Productivity: Speeds up the drafting process.\nError Reduction: Ensures high-quality, error-free documents.\nCustomization: Provides personalized drafting experience.\n\nTechnical Capabilities\nAI Algorithms: Utilizes NLP and machine learning for accurate drafting.\nTemplate-Based Drafting: Ensures consistency and precision.\n\nUser Interaction\nUser-Friendly Interface: Intuitive design for easy navigation.\nReal-Time Feedback: Provides suggestions for improving drafts.\n\nImplementation Details\nIntegration: Compatible with legal practice management software.\nSecurity: Ensures data privacy and security.\nSupport: Offers support and training resources.\n\nUsage Scenarios\nContract Creation\nLegal Agreements\nCompliance Documents\n\nConclusion\nThe Legal Drafter module transforms the document drafting process, making it faster, more accurate, and highly efficient.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Legal Drafter:\n\nFirst step is to provide the context of your case and proceed. \n\nAfter you accept the credit deduction, Our AI system will analyze the provided context.\n\nNow our system asks you to confirm the analysis results.\n\nSelect the type of document you need to draft and upload your case files.\n\nNext, our system will analyze and process the uploaded file accordingly.\n\nThen, select the reference statement that best fits your needs.\n\nUpload any reference documents if you have, or use our system to generate references.\n\nNow select the reference documents that was generated by our AI system.\n\nYou need to chat with our system and answer some questions about the document and you can skip after answering 5 questions.\n\nThen our system will perform the final processing based on your chat.\n\nFinally, you can see the Drafted document. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/oUAQURa110k?si=X-845vnoL29Yw1pn"
    },
    {
        "text": "Document Chat Module\nModule Overview\nThe Document Chat module of ADVOCASE AI allows users to interact with their legal documents through a conversational interface, enhancing accessibility and understanding.\n\nKey Features\nConversational Interface: Enables users to interact with documents via chat.\nInstant Insights: Provides immediate answers and insights based on document content.\nUser-Friendly Design: Easy-to-use interface for seamless interaction.\n\nBenefits\nEnhanced Accessibility: Makes document review and analysis more accessible.\nQuick Insights: Provides instant responses to user queries.\nUser Engagement: Engages users through an interactive chat experience.\n\nTechnical Capabilities\nNLP Technology: Uses natural language processing to understand user queries.\nReal-Time Processing: Analyzes and responds to queries in real-time.\n\nUser Interaction\nChat Interface: Intuitive design for easy interaction with documents.\nCustomizable Responses: Tailored responses based on user needs.\n\nImplementation Details\nIntegration: Compatible with document management systems.\nSecurity: Ensures data privacy and security.\nSupport: Comprehensive support and training resources.\n\nUsage Scenarios\nDocument Review\nLegal Research\nInformation Retrieval\n\nConclusion\nThe Document Chat module enhances user interaction with legal documents, providing instant insights and improving accessibility.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Document chat:\n\nFirst Step is to upload your document in any format and proceed.\n\nOur AI system will quickly review if the file is safe and meets the required conditions.\n\nAfter you accept the credit deduction, our system will start processing your document.\n\nNext, define your role in the case.\n\nUpload reference files if you have them, or you can skip this step or generate reference files.\n\nOur system will analyze the document based on the reference files and your role.\n\nThen, our system will continue processing your document.\n\nFinally, you can chat with the document and ask any questions related to it.",
        "youtube_link" : "https://youtu.be/fo4GglbNLrQ?si=ddCvswAA8sdOZzRF"
    },
    {
        "text": "Search Law Module\nModule Overview\nThe Search Law module of ADVOCASE AI provides powerful tools for searching and retrieving relevant legal statutes and regulations, streamlining legal research.\n\nKey Features\nComprehensive Search: Quickly retrieves relevant laws and regulations based on search parameters.\nAdvanced Filters: Allows users to filter search results for more precise information.\nReal-Time Updates: Ensures access to the latest legal information.\n\nBenefits\nTime Efficiency: Speeds up the process of finding relevant laws.\nAccurate Results: Ensures comprehensive and relevant search outcomes.\nUp-to-Date Information: Keeps users informed with the latest legal developments.\n\nTechnical Capabilities\nAI-Powered Search: Uses AI to identify and retrieve relevant laws.\nData Analysis: Analyzes legal texts to highlight important information.\n\nUser Interaction\nSearch Interface: User-friendly tools for efficient searching.\nDetailed Results: Provides comprehensive search results with relevant details.\n\nImplementation Details\nIntegration: Compatible with legal research databases.\nSecurity: Ensures data privacy and compliance.\nSupport: Offers support and training resources.\n\nUsage Scenarios\nLegal Research\nCase Preparation\nCompliance Checks\n\nConclusion\nThe Search Law module streamlines the process of finding relevant legal statutes and regulations, providing accurate and up-to-date information efficiently.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Search Law:\n\nWelcome to another explainer about amazing tools available at ADVOCASE.\n\nThis presentation guides you on how to search any law with just 3 simple steps.\n\nFirst Step is to describe your query.\n\nThen our system will start searching the law's.\n\nFinally, you can see the law's that applicable for your query. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/ZW7Qk2Nk2pw?si=mHG476T1dMbSEZQD"
    },
    {
        "text": "Document Translate Module\nModule Overview\nThe Document Translate module of ADVOCASE AI offers powerful translation tools for converting legal documents into multiple languages, ensuring accuracy and legal compliance.\n\nKey Features\nAccurate Translation: Provides precise translations of legal documents.\nMultiple Languages: Supports translation into various languages.\nLegal Terminology: Ensures correct usage of legal terms and jargon.\n\nBenefits\nEnhanced Accessibility: Makes legal documents accessible to non-native speakers.\nAccurate Translations: Ensures legal compliance and accuracy.\nTime Efficiency: Speeds up the translation process.\n\nTechnical Capabilities\nNLP Technology: Uses natural language processing for accurate translations.\nTerminology Database: Maintains a database of legal terms for precision.\n\nUser Interaction\nUser-Friendly Interface: Easy-to-use translation tools.\nCustomization Options: Allows users to specify translation preferences.\n\nImplementation Details\nIntegration: Compatible with document management systems.\nSecurity: Ensures data privacy and security.\nSupport: Comprehensive support and training resources.\n\nUsage Scenarios\nDocument Translation\nLegal Research\nCompliance Checks\n\nConclusion\nThe Document Translate module provides accurate and efficient translation of legal documents, ensuring accessibility and compliance.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Document Translator:\n\nWelcome to another explainer about amazing tools available at ADVOCASE.\n\nThis presentation guides you on how to translate any document into English with just 4 simple steps.\n\nFirst Step is to upload your document in any format and proceed.\n\nOur AI system will quickly review if the file is safe and meets the required conditions.\n\nAfter you accept credit deduction, our system will start translating your document.\n\nFinally, you can see the translated document. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/HIRDLpcBaPo?si=FBtN0pr2rdaG_RvW"
    },
    {
        "text": "Contract Analysis Module\nModule Overview\nThe Contract Analysis module of ADVOCASE AI automates the review and analysis of contracts, identifying key terms, conditions, and potential risks.\n\nKey Features\nAutomated Review: Quickly analyzes contracts for key terms and conditions.\nRisk Identification: Identifies potential risks and inconsistencies.\nDetailed Reports: Generates comprehensive reports on contract analysis.\n\nBenefits\nTime Efficiency: Speeds up the contract review process.\nAccurate Analysis: Ensures thorough and accurate review.\nRisk Mitigation: Identifies and mitigates potential risks.\n\nTechnical Capabilities\nAI Algorithms: Utilizes advanced algorithms for contract analysis.\nData Integration: Integrates data from multiple sources for comprehensive analysis.\n\nUser Interaction\nInteractive Dashboard: User-friendly interface for easy navigation.\nCustomizable Reports: Tailored reports based on contract specifics.\n\nImplementation Details\nIntegration: Compatible with contract management systems.\nSecurity: Ensures data privacy and compliance.\nSupport: Provides support and training resources.\n\nUsage Scenarios\nContract Review\nRisk Assessment\nCompliance Checks\n\nConclusion\nThe Contract Analysis module automates and enhances the contract review process, providing accurate analysis and identifying potential risks efficiently.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Contract Analysis:\n\nFirst Step is to upload your document in any format and proceed.\n\nOur AI system will quickly review if the file is safe and meets the required conditions.\n\nAfter you accept credit deduction, our system will start analyzing your document for contract analysis.\n\nFinally, you will see the overall contract analysis and a clause-by-clause analysis. You can also download the analysis for future reference.",
        "youtube_link" : "https://youtu.be/evaWfHMy648?si=QFRvtt81SABxVYSv"
    },
    {
        "text": "Document Rewriter Module\nModule Overview\nThe Document Rewriter module of ADVOCASE AI provides tools to rephrase and rewrite legal documents, ensuring clarity, precision, and compliance.\n\nKey Features\nAutomated Rewriting: Quickly rephrases and rewrites legal documents.\nClarity and Precision: Ensures clear and precise language.\nCompliance: Maintains legal compliance and accuracy.\n\nBenefits\nEnhanced Readability: Improves the clarity of legal documents.\nAccurate Rewriting: Ensures precision and compliance.\nTime Efficiency: Speeds up the rewriting process.\n\nTechnical Capabilities\nNLP Technology: Uses natural language processing for accurate rewriting.\nTerminology Database: Maintains a database of legal terms for precision.\n\nUser Interaction\nUser-Friendly Interface: Easy-to-use rewriting tools.\nCustomization Options: Allows users to specify rewriting preferences.\n\nImplementation Details\nIntegration: Compatible with document management systems.\nSecurity: Ensures data privacy and security.\nSupport: Comprehensive support and training resources.\n\nUsage Scenarios\nDocument Rewriting\nLegal Drafting\nCompliance Checks\n\nConclusion\nThe Document Rewriter module enhances the readability and accuracy of legal documents, ensuring clarity and compliance.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Document Rewriter:\n\nFirst Step is to upload your document in any format and proceed.\n\nOur AI system will quickly review if the file is safe and meets the required conditions.\n\nNext, select the presets you want to use for the rewritten document.\n\nAfter you accept the credit deduction, our system will start processing your document.\n\nFinally, you will see the rewritten version of your document, which you can also download for future reference.",
        "youtube_link" : "https://youtu.be/C7xG4cyE96I?si=uYxxr3VAdc9kFO1z"
    },
    {
        "text": "Legal Argument Generator Module\nModule Overview\nThe Legal Argument Generator module of ADVOCASE AI assists in formulating strong legal arguments by analyzing relevant laws, precedents, and case specifics.\n\nKey Features\nArgument Formulation: Generates strong legal arguments based on analysis.\nPrecedent Identification: Identifies relevant case law and precedents.\nComprehensive Reports: Provides detailed argumentation reports.\n\nBenefits\nIn-Depth Analysis: Ensures thorough understanding of legal issues.\nStrong Arguments: Helps in formulating effective legal arguments.\nAccurate Analysis: Provides reliable and well-supported arguments.\n\nTechnical Capabilities\nAI Algorithms: Utilizes advanced algorithms for argument formulation.\nData Integration: Integrates data from multiple sources for comprehensive analysis.\n\nUser Interaction\nInteractive Dashboard: User-friendly interface for easy navigation.\nCustomizable Reports: Tailored argumentation reports based on specific requirements.\n\nImplementation Details\nIntegration: Compatible with legal research databases.\nSecurity: Ensures data privacy and compliance.\nSupport: Provides support and training resources.\n\nUsage Scenarios\nLegal Strategy Formulation\nCase Preparation\nCourt Presentations\n\nConclusion\nThe Legal Argument Generator module provides strong and well-supported legal arguments, enhancing legal strategy and case preparation.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using legal Argument Generator:\n\nFirst Step is to write your query and then proceed.\n\nOur AI system will quickly analyzes your query and shows you the analysis result.\n\nAfter you verify the analysis result, just click continue.\n\nNext, upload all the required documents.\n\nOur AI system will quickly process your documents.\n\nNow upload the required Issue document and proceed.\n\nOur system will analyze and process your document and start generating argument.\n\nFinally, your argument will be generated and you can download it to your device for future references.",
        "youtube_link" : "https://youtu.be/c4yEjPVZ5cg?si=cyQE2pKiXmZWOYbw"
    },
    {
        "text": "Document Issue Spotter Module\nModule Overview\nThe Document Issue Spotter module of ADVOCASE AI automates the identification of potential issues and inconsistencies in legal documents, ensuring accuracy and compliance.\n\nKey Features\nAutomated Issue Spotting: Quickly identifies potential issues and inconsistencies.\nRisk Identification: Highlights potential risks and areas of concern.\nDetailed Reports: Generates comprehensive issue-spotting reports.\n\nBenefits\nTime Efficiency: Speeds up the issue-spotting process.\nAccurate Identification: Ensures thorough and accurate identification of issues.\nRisk Mitigation: Helps in mitigating potential risks.\n\nTechnical Capabilities\nAI Algorithms: Utilizes advanced algorithms for issue spotting.\nData Integration: Integrates data from multiple sources for comprehensive analysis.\n\nUser Interaction\nInteractive Dashboard: User-friendly interface for easy navigation.\nCustomizable Reports: Tailored issue-spotting reports based on document specifics.\n\nImplementation Details\nIntegration: Compatible with document management systems.\nSecurity: Ensures data privacy and compliance.\nSupport: Provides support and training resources.\n\nUsage Scenarios\nDocument Review\nRisk Assessment\nCompliance Checks\n\nConclusion\nThe Document Issue Spotter module automates and enhances the process of identifying potential issues in legal documents, ensuring accuracy and compliance.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Document Issue Spotter:\n\nFirst Step is to upload your document in any format & proceed.\n\nOur AI system will quickly review if the file is safe and meets the required conditions.\n\nAfter you accept credit deduction, our system will start analyzing your document for legal issues.\n\nFinally, you can see the identified issues categorized into three risk levels. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/Da4AgLn7sEM?si=1oVVgheUtvpDrPt_"
    },
    {
        "text": "Agreement Writer Module\nModule Overview\nThe Agreement Writer module of ADVOCASE AI automates the creation of legal agreements, ensuring precision, efficiency, and compliance.\n\nKey Features\nAutomated Drafting: Generates legal agreements quickly with minimal manual input.\nTemplate Library: Offers a variety of templates for different types of agreements.\nCustomization Options: Allows users to add detailed specifications and personal inputs.\n\nBenefits\nEnhanced Productivity: Speeds up the agreement drafting process.\nError Reduction: Ensures high-quality, error-free agreements.\nCustomization: Provides personalized drafting experience.\n\nTechnical Capabilities\nAI Algorithms: Utilizes NLP and machine learning for accurate drafting.\nTemplate-Based Drafting: Ensures consistency and precision.\n\nUser Interaction\nUser-Friendly Interface: Intuitive design for easy navigation.\nReal-Time Feedback: Provides suggestions for improving drafts.\n\nImplementation Details\nIntegration: Compatible with legal practice management software.\nSecurity: Ensures data privacy and security.\nSupport: Offers support and training resources.\n\nUsage Scenarios\nContract Creation\nLegal Agreements\nCompliance Documents\n\nConclusion\nThe Agreement Writer module transforms the agreement drafting process, making it faster, more accurate, and highly efficient.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Agreement Writer:\n\nFirst Step is to select the type of agreement from over 340 types.\n\nAfter you accept credit deduction, You need to chat with our system and answer some questions about the agreement and you can skip after 5 questions.\n\nNow our system will start generating your agreement.\n\nFinally, you can see the generated agreement. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/SV-SDA3-lcw?si=dSUQDX3fXlIwZsDK"
    },
    {
        "text": "Simplify Document Module\nModule Overview\nThe Simplify Document module of ADVOCASE AI provides tools to simplify and condense legal documents, ensuring clarity and ease of understanding.\n\nKey Features\nAutomated Simplification: Quickly simplifies and condenses legal documents.\nClarity and Precision: Ensures clear and precise language.\nCompliance: Maintains legal compliance and accuracy.\n\nBenefits\nEnhanced Readability: Improves the clarity of legal documents.\nAccurate Simplification: Ensures precision and compliance.\nTime Efficiency: Speeds up the simplification process.\n\nTechnical Capabilities\nNLP Technology: Uses natural language processing for accurate simplification.\nTerminology Database: Maintains a database of legal terms for precision.\n\nUser Interaction\nUser-Friendly Interface: Easy-to-use simplification tools.\nCustomization Options: Allows users to specify simplification preferences.\n\nImplementation Details\nIntegration: Compatible with document management systems.\nSecurity: Ensures data privacy and security.\nSupport: Comprehensive support and training resources.\n\nUsage Scenarios\nDocument Simplification\nLegal Drafting\nCompliance Checks\n\nConclusion\nThe Simplify Document module enhances the readability and accuracy of legal documents, ensuring clarity and compliance.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Document Simplifier:\n\nFirst Step is to upload your document in any format, choose the language you want and proceed.\n\nOur AI system will quickly review if the file is safe and meets the required conditions.\n\nAfter you accept credit deduction, our system will start simplifying your document.\n\nFinally, you can see the simplified document. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/bGoKr0UYHXs?si=A4eamlKrPZez-2VE"
    },
    {
        "text": "Search Judgements Module\nModule Overview\nThe Search Judgements module of ADVOCASE AI provides powerful tools for searching and retrieving relevant judicial decisions, streamlining legal research.\n\nKey Features\nComprehensive Search: Quickly retrieves relevant judicial decisions based on search parameters.\nAdvanced Filters: Allows users to filter search results for more precise information.\nReal-Time Updates: Ensures access to the latest judicial decisions.\n\nBenefits\nTime Efficiency: Speeds up the process of finding relevant judgements.\nAccurate Results: Ensures comprehensive and relevant search outcomes.\nUp-to-Date Information: Keeps users informed with the latest judicial developments.\n\nTechnical Capabilities\nAI-Powered Search: Uses AI to identify and retrieve relevant judgements.\nData Analysis: Analyzes judicial texts to highlight important information.\n\nUser Interaction\nSearch Interface: User-friendly tools for efficient searching.\nDetailed Results: Provides comprehensive search results with relevant details.\n\nImplementation Details\nIntegration: Compatible with legal research databases.\nSecurity: Ensures data privacy and compliance.\nSupport: Offers support and training resources.\n\nUsage Scenarios\nLegal Research\nCase Preparation\nPrecedent Identification\n\nConclusion\nThe Search Judgements module streamlines the process of finding relevant judicial decisions, providing accurate and up-to-date information efficiently.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Search Judgements Module:\n\n1. Describe the judgement you want: Provide details about the specific judgement you are looking for, including relevant keywords, case details, or any other relevant information.\n\n2. Select number of Judgements you want: Choose the number of judgements you want to retrieve, indicating how many relevant cases you wish to review.\n\n3. Enter your role and proceed: Specify your role or affiliation, such as lawyer, legal researcher, or student, and proceed with the search.\n\nOur AI system will quickly process your query and search for judgements.\n\nFinally, you can have a list of Judgements. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/R1Tf2gwqkzA?si=vWGmE3yCS2kshYb3"
    },
    {
        "text": "Search Dictionary Module\nModule Overview\nThe Search Dictionary module of ADVOCASE AI provides access to a comprehensive legal dictionary, enhancing understanding and precision in legal writing.\n\nKey Features\nComprehensive Dictionary: Provides definitions of legal terms and concepts.\nSearch Functionality: Allows users to search for specific terms.\nReal-Time Updates: Ensures access to the latest legal terminology.\n\nBenefits\nEnhanced Understanding: Improves comprehension of legal terminology.\nPrecision in Writing: Ensures correct usage of legal terms and concepts.\nUp-to-Date Information: Keeps users informed with the latest legal terminology.\n\nTechnical Capabilities\nDatabase Management: Maintains a comprehensive database of legal terms.\nSearch Algorithms: Enables efficient searching for terms and concepts.\n\nUser Interaction\nSearch Interface: User-friendly tools for efficient searching.\nDetailed Definitions: Provides comprehensive definitions of legal terms.\n\nImplementation Details\nIntegration: Compatible with legal research platforms.\nSecurity: Ensures data privacy and compliance.\nSupport: Offers support and training resources.\n\nUsage Scenarios\nLegal Writing\nDocument Review\nResearch\n\nConclusion\nThe Search Dictionary module provides access to a comprehensive legal dictionary, enhancing understanding and precision in legal writing.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using legal dictionary:\n\nFirst Step is to type a legal term to access detailed definitions and related legal concepts.\n\nThen our system will start searching.\n\nFinally, you can see the detailed definitions and related legal concepts. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/vHOVpBPWdyo?si=lrLLeQb9GWlODxKM"
    },
    {
        "text": "Quick Writer Module\nModule Overview\nThe Quick Writer module of ADVOCASE AI provides tools for rapid drafting and writing of legal documents, ensuring efficiency and accuracy.\n\nKey Features\nRapid Drafting: Quickly drafts legal documents with minimal manual input.\nTemplate Library: Offers a variety of templates for different legal documents.\nCustomization Options: Allows users to add detailed specifications and personal inputs.\n\nBenefits\nEnhanced Productivity: Speeds up the drafting process.\nError Reduction: Ensures high-quality, error-free documents.\nCustomization: Provides personalized drafting experience.\n\nTechnical Capabilities\nAI Algorithms: Utilizes NLP and machine learning for accurate drafting.\nTemplate-Based Drafting: Ensures consistency and precision.\n\nUser Interaction\nUser-Friendly Interface: Intuitive design for easy navigation.\nReal-Time Feedback: Provides suggestions for improving drafts.\n\nImplementation Details\nIntegration: Compatible with legal practice management software.\nSecurity: Ensures data privacy and security.\nSupport: Offers support and training resources.\n\nUsage Scenarios\nContract Creation\nLegal Agreements\nCompliance Documents\n\nConclusion\nThe Quick Writer module transforms the drafting process, making it faster, more accurate, and highly efficient.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Quick writer:\n\nFirst Step is to describe your query.\n\nAfter you accept credit deduction, You need to chat with our system and answer some questions about the document and you can skip after 5 questions.\n\nNow our system will start generating your document.\n\nFinally, you can see the quickly generated document. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/LfqT9E1ij5w?si=lI03JXXgfLphWWDY"
    },
    {
        "text": "Cross Examination Module\nModule Overview\nThe Cross Examination module of ADVOCASE AI provides tools to prepare and simulate cross-examinations, enhancing legal preparation and strategy.\n\nKey Features\nSimulation Tools: Provides realistic simulations of cross-examinations.\nQuestion Bank: Offers a comprehensive bank of cross-examination questions.\nPerformance Feedback: Provides feedback and analysis of performance.\n\nBenefits\nEnhanced Preparation: Improves readiness for cross-examinations.\nRealistic Practice: Provides a realistic environment for practicing cross-examinations.\nPerformance Improvement: Helps in improving cross-examination skills through feedback.\n\nTechnical Capabilities\nAI-Powered Simulations: Uses AI to simulate realistic cross-examination scenarios.\nData Analysis: Analyzes performance and provides feedback.\n\nUser Interaction\nUser-Friendly Interface: Intuitive design for easy navigation.\nCustomizable Scenarios: Allows users to customize simulation scenarios.\n\nImplementation Details\nIntegration: Compatible with legal education platforms.\nSecurity: Ensures data privacy and compliance.\nSupport: Comprehensive support and training resources.\n\nUsage Scenarios\nLegal Education\nCourt Preparation\nSkill Enhancement\n\nConclusion\nThe Cross Examination module provides realistic simulations and tools to prepare for cross-examinations, enhancing legal strategy and preparation.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Cross Examination:\n\nFirst step is to upload your document in any format and proceed.\n\nOur AI system will quickly check if the file is safe and meets the required conditions.\n\nAfter you accept the credit deduction, our system will start processing your document.\n\nNext, define your role in the case and upload the chief affidavit file.\n\nOur system will then process your document based on your role and the chief affidavit.\n\nFinally, you will see the cross-examination questions related to the case, which you can also download for future reference.",
        "youtube_link" : "https://youtu.be/T4GZyARH8E0?si=NmKNjO_gkfK-7Shl"
    },
    {
        "text": "Legal Procedures Module\nModule Overview\nThe Legal Procedures module of ADVOCASE AI provides comprehensive tools for understanding and managing legal procedures, ensuring compliance and accuracy.\n\nKey Features\nProcedure Library: Provides a comprehensive library of legal procedures.\nStep-by-Step Guidance: Offers detailed guidance for each step of the procedure.\nCompliance Checks: Ensures procedures are compliant with relevant laws and regulations.\n\nBenefits\nEnhanced Understanding: Improves comprehension of legal procedures.\nAccurate Guidance: Ensures precision and compliance.\nTime Efficiency: Speeds up the process of managing legal procedures.\n\nTechnical Capabilities\nAI-Powered Guidance: Uses AI to provide accurate and detailed guidance.\nProcedure Database: Maintains an up-to-date database of legal procedures.\n\nUser Interaction\nUser-Friendly Interface: Easy-to-use tools for managing procedures.\nCustomization Options: Allows users to specify procedure preferences.\n\nImplementation Details\nIntegration: Compatible with legal practice management software.\nSecurity: Ensures data privacy and security.\nSupport: Comprehensive support and training resources.\n\nUsage Scenarios\nLegal Research\nCase Management\nCompliance Checks\n\nConclusion\nThe Legal Procedures module enhances the understanding and management of legal procedures, ensuring accuracy and compliance.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Legal Procedure:\n\nFirst Step is to upload your document in any format and proceed.\n\nOur AI system will quickly review if the file is safe and meets the required conditions.\n\nAfter you accept credit deduction, our system will start analyzing your document for legal procedure.\n\nFinally, you can see the legal procedure of your document in various steps. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/49IIusNs-8k?si=wWL4EH5hqKnPJhsm"
    },
    {
        "text": "AI Lawyers Module\nModule Overview\nThe AI Lawyers module of ADVOCASE AI leverages artificial intelligence to provide automated legal assistance, enhancing productivity and accuracy.\n\nKey Features\nAutomated Assistance: Provides automated legal advice and support.\nAdvanced Algorithms: Utilizes AI algorithms for accurate legal analysis.\nReal-Time Updates: Ensures access to the latest legal information.\n\nBenefits\nEnhanced Productivity: Reduces manual effort and enhances efficiency.\nAccurate Assistance: Provides reliable and well-supported legal advice.\nUp-to-Date Information: Keeps users informed with the latest legal developments.\n\nTechnical Capabilities\nAI Algorithms: Utilizes advanced algorithms for legal analysis.\nData Integration: Integrates data from multiple sources for comprehensive analysis.\n\nUser Interaction\nUser-Friendly Interface: Intuitive design for easy navigation.\nCustomizable Responses: Tailored legal advice based on user needs.\n\nImplementation Details\nIntegration: Compatible with legal practice management software.\nSecurity: Ensures data privacy and compliance.\nSupport: Provides support and training resources.\n\nUsage Scenarios\nLegal Research\nCase Preparation\nClient Consultations\n\nConclusion\nThe AI Lawyers module provides automated legal assistance, enhancing productivity and ensuring accurate and up-to-date legal advice.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Ai lawyers:\n\nWelcome to another explainer about amazing tools available at ADVOCASE.\n\nThis presentation guides you on how to Chat with Ai Lawyers with just 3 simple steps.\n\nFirst Step is Select our specialized AI Lawyer related to your Query.\n\nPlease begin a new chat to start your session.\n\nFinally, now you can type in your legal question and get immediate, precise answers from our AI lawyer.",
        "youtube_link" : "https://youtu.be/9LDW2WHAHq8?si=2Reh9Dt3OLrgMz73"
    },
    {
        "text": "Bail Application Module\n\nModule Overview\nThe Bail Application module of ADVOCASE AI streamlines the process of drafting and filing bail applications, ensuring accuracy, efficiency, and compliance with legal standards.\n\nKey Features\nAutomated Drafting: Generates bail applications quickly with minimal manual input.\nTemplate Library: Offers a variety of templates for different types of bail applications.\nCustomization Options: Allows users to add detailed specifications and personal inputs.\nCompliance Checks: Ensures that applications comply with relevant legal requirements and standards.\n\nBenefits\nEnhanced Productivity: Speeds up the drafting process, allowing legal professionals to focus on other important tasks.\nError Reduction: Ensures high-quality, error-free applications by automating the drafting process.\nCustomization: Provides a personalized drafting experience, accommodating specific case details and requirements.\nCompliance: Guarantees that applications meet legal standards, reducing the risk of rejection or delays.\n\nTechnical Capabilities\nAI Algorithms: Utilizes NLP and machine learning for accurate and efficient drafting.\nTemplate-Based Drafting: Ensures consistency and precision in the application process.\nData Integration: Integrates data from multiple sources for comprehensive analysis and drafting.\nCompliance Engine: Checks applications against current legal standards to ensure compliance.\n\nUser Interaction\nUser-Friendly Interface: Intuitive design for easy navigation and use.\nReal-Time Feedback: Provides suggestions for improving drafts, ensuring accuracy and completeness.\nInteractive Dashboard: Allows users to manage and track the status of bail applications.\nCustomizable Fields: Enables users to input specific details pertinent to each case, ensuring a tailored application.\n\nImplementation Details\nIntegration: Compatible with legal practice management software and document management systems.\nSecurity: Ensures data privacy and compliance with legal and ethical standards.\nSupport: Offers comprehensive support and training resources, including user guides and customer service.\n\nUsage Scenarios\nCriminal Defense: Assists defense attorneys in preparing bail applications efficiently.\nCase Management: Streamlines the process of managing multiple bail applications.\nLegal Consultation: Enhances the ability to provide accurate and timely legal advice regarding bail.\nCourt Filings: Facilitates the preparation and submission of bail applications to courts.\n\nConclusion\nThe Bail Application module transforms the process of drafting and filing bail applications, making it faster, more accurate, and highly efficient. By leveraging advanced AI algorithms and ensuring compliance with legal standards, this module enhances the productivity and effectiveness of legal professionals.",
        "table_name" : "modulesdata",
        "use_steps" : "Steps for using Legal Procedure:\n\nFirst Step is to upload your document in any format and proceed.\n\nOur AI system will quickly review if the file is safe and meets the required conditions.\n\nAfter you accept credit deduction, our system will start analyzing your document for legal procedure.\n\nFinally, you can see the legal procedure of your document in various steps. And you can also download the same to your device for future reference.",
        "youtube_link" : "https://youtu.be/_rhRMp5eD4Q?si=q-w2Phg0-P-Z8wq8"
    }
]


# Function to insert data into the FastAPI endpoint
def insert_data(data):
    try:
        response = requests.post(endpoint_url, json=data)
        if response.status_code == 200:
            print("Data added successfully:", data)
        else:
            print("Error adding data:", response.text)
    except Exception as e:
        print("Exception occurred:", str(e))

# Insert each data entry one by one
for data_entry in data_list:
    insert_data(data_entry)
